service: swing-notes-api

provider:
  name: aws
  runtime: nodejs22.x
  region: eu-north-1
  stage: ${opt:stage, 'dev'}
  environment:
    NOTES_TABLE: ${self:service}-notes-${self:provider.stage}
    API_KEY: ${env:API_KEY, 'your-secret-api-key'}

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource: "arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.NOTES_TABLE}"

functions:
  # Notes functions
  getNotes:
    handler: src/handlers/getNotes.handler
    events:
      - http:
          path: api/notes/user/{username}
          method: get

  createNote:
    handler: src/handlers/createNote.handler
    events:
      - http:
          path: api/notes/
          method: post

  updateNote:
    handler: src/handlers/updateNote.handler
    events:
      - http:
          path: api/notes/{id}
          method: put

  deleteNote:
    handler: src/handlers/deleteNote.handler
    events:
      - http:
          path: api/notes/{id}
          method: delete

resources:
  Resources:
    NotesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.NOTES_TABLE}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: username
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: username-index
            KeySchema:
              - AttributeName: username
                KeyType: HASH
            Projection:
              ProjectionType: ALL

plugins:
  - serverless-offline
  - serverless-dynamodb-local

custom:
  dynamodb:
    stages:
      - dev
    start:
      migrate: true
      seed: false
      port: 8000
      inMemory: true